import ProgramDetailTemplate from './ProgramDetailTemplate'
import { getNextBatchDate } from '../lib/programUtils'

function CybersecurityPage() {
  const programData = {
    title: 'Cybersecurity',
    subtitle: 'Security Engineering & Ethical Defense',
    category: 'Technology • Security',
    description: 'Learn practical cybersecurity from fundamentals to advanced defense. Build skills in network security, web security, threat analysis, and incident response.',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1000&h=600&fit=crop&q=95',
    path: '/programs/cybersecurity',
    enrollUrl: 'https://forms.gle/DyDigMebuEbwED347?program=cybersecurity',
    duration: '3 months',
    level: 'Beginner to Advanced',
    enrolled: '640+ enrolled',
    quickStats: [
      { value: '89%', label: 'Placement Rate', icon: '🎯' },
      { value: '4.7★', label: 'Student Rating', icon: '⭐' },
      { value: '640+', label: 'Alumni Network', icon: '👥' },
      { value: '30+', label: 'Labs & Projects', icon: '💼' },
    ],
    topics: [
      { title: 'Security Fundamentals', description: 'CIA triad, attack vectors, and risk basics' },
      { title: 'Network Security', description: 'Firewalls, protocols, and traffic analysis' },
      { title: 'Web Security', description: 'OWASP Top 10 and secure web patterns' },
      { title: 'Ethical Testing', description: 'Controlled vulnerability discovery and reporting' },
      { title: 'Cloud Security', description: 'IAM, secrets, and cloud hardening basics' },
      { title: 'Incident Response', description: 'Detection, containment, and post-incident workflows' },
    ],
    curriculum: [
      { title: 'Security Foundations', description: 'Understand cyber threats and controls', duration: '1 week', phase: 'foundation', topics: ['Threat Landscape', 'Security Principles', 'Risk Assessment', 'Compliance Basics'] },
      { title: 'Network Defense', description: 'Monitor and secure network layers', duration: '1 week', phase: 'foundation', topics: ['TCP/IP', 'Firewall Rules', 'Packet Analysis', 'IDS/IPS'] },
      { title: 'Web & App Security', description: 'Defend modern applications', duration: '1 week', phase: 'foundation', topics: ['OWASP Top 10', 'Auth Hardening', 'Session Security', 'Input Validation'] },
      { title: 'Foundation Project', description: 'Security audit of sample app stack', duration: '1 week', phase: 'foundation', topics: ['Vulnerability Scan', 'Risk Report', 'Fix Plan', 'Retest'] },
      { title: 'Offensive Security Basics', description: 'Safe testing in controlled labs', duration: '1 week', phase: 'intermediate', topics: ['Recon', 'Enumeration', 'Exploit Concepts', 'Posture Checks'] },
      { title: 'SIEM and Monitoring', description: 'Detect and investigate security events', duration: '1 week', phase: 'intermediate', topics: ['Log Pipelines', 'Detection Rules', 'Alerting', 'Forensics Basics'] },
      { title: 'Intermediate Project', description: 'SOC-style monitoring workflow', duration: '1 week', phase: 'intermediate', topics: ['Use Cases', 'Playbooks', 'Response Steps', 'Report'] },
      { title: 'Cloud and DevSecOps', description: 'Shift-left security and cloud controls', duration: '1 week', phase: 'advanced', topics: ['IAM', 'Secrets', 'Container Security', 'Policy as Code'] },
      { title: 'Capstone Project', description: 'End-to-end security posture implementation', duration: '1 week', phase: 'advanced', topics: ['Architecture Review', 'Threat Model', 'Controls', 'Executive Summary'] },
    ],
    skills: ['Network Security', 'OWASP', 'SIEM', 'Incident Response', 'Threat Modeling', 'Cloud Security'],
    projects: [
      { title: 'Web App Security Audit', description: 'Assess a web application and produce remediation roadmap.', technologies: ['Burp Suite', 'OWASP ZAP', 'Nmap'], image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500' },
      { title: 'SOC Monitoring Dashboard', description: 'Create event detection and alert triage workflow.', technologies: ['ELK', 'Sigma Rules', 'Python'], image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500' },
      { title: 'Cloud Security Hardening Toolkit', description: 'Implement IAM controls, secrets rotation, and configuration baselines for multi-cloud workloads.', technologies: ['AWS', 'Terraform', 'CloudTrail', 'Python'], image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500' },
      { title: 'Incident Response Automation', description: 'Build automated playbooks for triage, containment, and post-incident reporting workflows.', technologies: ['SOAR', 'Python', 'SIEM APIs', 'MITRE ATT&CK'], image: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=500' },
    ],
    batchInfo: { nextBatchDate: getNextBatchDate(), seatsAvailable: 16, totalSeats: 30 },
    learningFormat: {
      mode: 'Live + Recorded',
      batchOptions: ['Weekend Batch', 'Weekday Evening Batch'],
      groupSize: '20-25 students per batch',
      doubtsResolution: 'Weekly security clinic + community support',
      communityAccess: 'Access to cybersecurity learner forum and labs',
      liveSessionDuration: '2 hours per session',
      additionalSupport: 'Capstone review and interview prep',
    },
    prerequisites: {
      required: ['Basic computer usage', 'Curiosity for systems', 'Ethical mindset'],
      recommended: ['Networking basics', 'Linux familiarity', 'Any scripting exposure'],
      idealFor: ['IT support professionals', 'Developers interested in security', 'Fresh graduates'],
    },
    cost: 'Starting at ₹1,499',
    costDetails: {
      foundation: { name: 'Foundation', price: '₹1,499', duration: '3 months', features: ['Recorded modules', 'Practice labs', 'Community access'] },
      professional: { name: 'Professional', price: '₹4,999', duration: '3 months', features: ['Live sessions', 'Lab projects', 'Mentor support'] },
      premium: { name: 'Premium', price: '₹7,999', duration: '3 months', features: ['Advanced mentoring', 'Capstone guidance', 'Career support'] },
    },
    pricingComparison: [
      { feature: 'Program Duration', foundation: '3 months', professional: '3 months', premium: '3 months' },
      { feature: 'Content Access', foundation: 'Foundation only', professional: 'All levels', premium: 'All levels' },
      { feature: 'Live Sessions', foundation: '❌', professional: '40+ hours', premium: '60+ hours' },
      { feature: 'Hands-on Labs & Projects', foundation: '3 labs', professional: '5 labs', premium: '8+ labs' },
      { feature: 'Capstone Project', foundation: '❌', professional: '❌', premium: '✅' },
      { feature: '1-on-1 Mentorship', foundation: '❌', professional: '❌', premium: '✅ Unlimited' },
      { feature: 'Interview Preparation', foundation: '❌', professional: 'Basic', premium: 'Advanced + Mock' },
      { feature: 'Placement Assistance', foundation: '❌', professional: 'Basic', premium: '✅ 100%' },
      { feature: 'Resume Building', foundation: '❌', professional: '✅', premium: '✅ + LinkedIn' },
      { feature: 'Industry Certifications', foundation: '1 certification', professional: '2 certifications', premium: '3+ certifications' },
      { feature: 'Job Referrals', foundation: '❌', professional: '❌', premium: '✅ Priority' },
      { feature: 'Lifetime Access', foundation: '✅', professional: '✅', premium: '✅' },
      { feature: 'Community Support', foundation: 'Forum only', professional: '✅ Active', premium: '✅ + Alumni Network' },
    ],
    competitorComparison: [
      { feature: 'Price', venura: '₹4,999 - ₹7,999', coursera: '₹16,000+', udemy: '₹3,999', bootcamp: '₹1,50,000+' },
      { feature: 'Duration', venura: '3 months', coursera: '3 months', udemy: '3 months', bootcamp: '3 months' },
      { feature: 'Live Sessions', venura: '60+ hours', coursera: 'Limited', udemy: 'None', bootcamp: '180+ hours' },
      { feature: 'Placement Support', venura: '100% (Premium)', coursera: 'None', udemy: 'None', bootcamp: 'Yes' },
      { feature: '1-on-1 Mentorship', venura: 'Unlimited (Premium)', coursera: 'None', udemy: 'None', bootcamp: 'Limited' },
      { feature: 'Hands-on Labs', venura: '8+ labs', coursera: '3-4 labs', udemy: '4-5 labs', bootcamp: '5-6 labs' },
      { feature: 'Job Referrals', venura: '100+ partners', coursera: 'None', udemy: 'None', bootcamp: '50+ partners' },
      { feature: 'Community', venura: 'Active 640+', coursera: 'Forum only', udemy: 'Limited', bootcamp: 'Batch only' },
      { feature: 'Certification', venura: 'Industry recognized', coursera: 'University backed', udemy: 'Platform certificate', bootcamp: 'Industry recognized' },
    ],
    jobRoles: ['Security Analyst', 'SOC Analyst', 'Vulnerability Analyst', 'Security Engineer (Junior)'],
    salaryRanges: [
      { role: 'Security Analyst', range: '₹5-10 LPA', experience: '0-2 years' },
      { role: 'SOC Analyst', range: '₹4.5-9 LPA', experience: '0-2 years' },
      { role: 'Vulnerability Analyst', range: '₹6-11 LPA', experience: '0-2 years' },
      { role: 'Security Engineer', range: '₹7-13 LPA', experience: '0-2 years' },
      { role: 'Cloud Security Associate', range: '₹7-14 LPA', experience: '0-2 years' },
      { role: 'Incident Response Analyst', range: '₹6-12 LPA', experience: '0-2 years' },
    ],
    hiringCompanies: ['Deloitte', 'KPMG', 'Accenture', 'TCS', 'Infosys', 'Wipro', 'IBM'],
    growthStats: [
      { value: '35%', label: 'Annual Growth', description: 'Cybersecurity role expansion' },
      { value: '700K+', label: 'Open Roles', description: 'Security opportunities globally' },
      { value: 'Critical', label: 'Business Priority', description: 'Security spending rising each year' },
    ],
    marketDataSource: [
      { label: 'WEF Cybersecurity Outlook', url: 'https://www.weforum.org/' },
      { label: 'ISC2 Workforce Study', url: 'https://www.isc2.org/Research/Workforce-Study' },
      { label: 'ENISA Threat Landscape', url: 'https://www.enisa.europa.eu/' },
    ],
    comparisonSource: [
      { label: 'Coursera Pricing', url: 'https://www.coursera.org/' },
      { label: 'Udemy Pricing', url: 'https://www.udemy.com/' },
      { label: 'Bootcamp Listings', url: 'https://www.coursereport.com/' },
    ],
    futureOutlook: 'Cybersecurity is now a board-level priority across industries, creating stable long-term demand for skilled defensive security professionals.',
    instructors: [
      { name: 'Siddharth Rao', role: 'Lead Security Mentor', experience: '11+ years', credentials: 'Ex-Red Team Consultant', image: 'https://ui-avatars.com/api/?name=Siddharth+Rao&background=0A2342&color=fff&size=200', specialization: 'Application Security' },
      { name: 'Neeraja Pillai', role: 'Cloud Security Instructor', experience: '9+ years in cloud defense', credentials: 'CCSP, Ex-AWS Security Team', image: 'https://ui-avatars.com/api/?name=Neeraja+Pillai&background=FF7A00&color=fff&size=200', specialization: 'Cloud Security & IAM' },
      { name: 'Akash Bhat', role: 'SOC Specialist Mentor', experience: '10+ years in threat operations', credentials: 'Ex-IBM Security Operations', image: 'https://ui-avatars.com/api/?name=Akash+Bhat&background=0A2342&color=fff&size=200', specialization: 'SIEM & Incident Response' },
    ],
    reviews: [
      { name: 'Pavan', role: 'Security Analyst', company: 'Accenture', image: 'https://ui-avatars.com/api/?name=Pavan&background=FF7A00&color=fff&size=200', rating: 5, text: 'Hands-on labs and mentoring were excellent. I transitioned into SOC within months.' },
      { name: 'Nisha Menon', role: 'SOC Analyst', company: 'Deloitte', image: 'https://ui-avatars.com/api/?name=Nisha+Menon&background=0A2342&color=fff&size=200', rating: 5, text: 'The incident response modules were super practical. I was job-ready right after the capstone.' },
      { name: 'Rahul Nair', role: 'Security Engineer', company: 'IBM', image: 'https://ui-avatars.com/api/?name=Rahul+Nair&background=FF7A00&color=fff&size=200', rating: 5, text: 'Excellent mentorship and real SOC workflows. The curriculum mirrors what teams use in production.' },
      { name: 'Karthik Iyer', role: 'Cloud Security Associate', company: 'Infosys', image: 'https://ui-avatars.com/api/?name=Karthik+Iyer&background=0A2342&color=fff&size=200', rating: 5, text: 'I loved the cloud security labs and policy-as-code exercises. Very relevant for modern security roles.' },
    ],
    certificatePreview: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
    faqs: [
      { question: 'Do I need prior security knowledge?', answer: 'No, we start from fundamentals and move progressively to practical security workflows.' },
      { question: 'Are labs included?', answer: 'Yes, practical lab exercises are included throughout the program.' },
      { question: 'Will I learn ethical hacking tools?', answer: 'Yes. You will work with industry tools in controlled lab environments and learn proper reporting and remediation practices.' },
      { question: 'Can I switch between plans later?', answer: 'Yes. You can upgrade anytime by paying the difference and unlock additional support and placement features instantly.' },
      { question: 'What if I miss live classes?', answer: 'All live sessions are recorded and available for lifetime access, so you can catch up anytime.' },
      { question: 'Is there placement support?', answer: 'Premium includes end-to-end placement support with resume reviews, mock interviews, and referral opportunities.' },
      { question: 'How much weekly time is required?', answer: 'We recommend 8-10 hours for Foundation and 12-15 hours for Professional/Premium to complete labs and projects comfortably.' },
    ],
  }

  return <ProgramDetailTemplate programData={programData} />
}

export default CybersecurityPage
