import ProgramDetailTemplate from './ProgramDetailTemplate'
import { getNextBatchDate } from '../lib/programUtils'

function JavaBackendPage() {
  const programData = {
    title: 'Java Backend Development',
    subtitle: 'Enterprise API & Microservices Engineering',
    category: 'Technology • Backend',
    description: 'Master Java backend engineering with Spring Boot, microservices, database design, distributed systems basics, and production-ready API development.',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1000&h=600&fit=crop&q=95',
    path: '/programs/java-backend',
    enrollUrl: 'https://forms.gle/DyDigMebuEbwED347?program=java-backend',
    duration: '3 months',
    level: 'Beginner to Advanced',
    enrolled: '820+ enrolled',
    quickStats: [
      { value: '91%', label: 'Placement Rate', icon: '🎯' },
      { value: '4.7★', label: 'Student Rating', icon: '⭐' },
      { value: '820+', label: 'Alumni Network', icon: '👥' },
      { value: '35+', label: 'Projects Built', icon: '💼' },
    ],
    topics: [
      { title: 'Core Java', description: 'OOP, collections, streams, and modern Java features' },
      { title: 'Spring Boot', description: 'Build scalable backend services with Spring ecosystem' },
      { title: 'REST APIs', description: 'Design and secure robust API contracts' },
      { title: 'Databases', description: 'Schema design, SQL optimization, and ORM' },
      { title: 'Microservices', description: 'Service decomposition and communication patterns' },
      { title: 'Testing & Deployment', description: 'JUnit, integration tests, and cloud deployment' },
    ],
    curriculum: [
      { title: 'Java Foundations', description: 'Strong base in Java programming', duration: '1 week', phase: 'foundation', topics: ['OOP', 'Collections', 'Exception Handling', 'Streams'] },
      { title: 'Spring Boot Core', description: 'Create production backend APIs', duration: '2 weeks', phase: 'foundation', topics: ['Spring MVC', 'Dependency Injection', 'Validation', 'Error Handling'] },
      { title: 'Persistence Layer', description: 'Data modeling and JPA', duration: '1 week', phase: 'foundation', topics: ['JPA', 'Hibernate', 'SQL', 'Transactions'] },
      { title: 'Foundation Project', description: 'Backend API with auth and persistence', duration: '1 week', phase: 'foundation', topics: ['JWT Auth', 'CRUD APIs', 'Role Access', 'Postman Testing'] },
      { title: 'Distributed Patterns', description: 'Scalable architecture basics', duration: '1 week', phase: 'intermediate', topics: ['Caching', 'Message Queues', 'Service Discovery', 'Config Management'] },
      { title: 'Microservices', description: 'Build independently deployable services', duration: '1 week', phase: 'intermediate', topics: ['Gateway', 'Inter-service Calls', 'Fault Tolerance', 'Observability'] },
      { title: 'Intermediate Project', description: 'Microservice commerce backend', duration: '1 week', phase: 'intermediate', topics: ['Order Service', 'Payment Service', 'Inventory Service', 'Tracing'] },
      { title: 'Testing & Security', description: 'Enterprise testing and secure APIs', duration: '1 week', phase: 'advanced', topics: ['JUnit', 'Integration Tests', 'OWASP Basics', 'API Security'] },
      { title: 'Capstone Project', description: 'Enterprise-grade backend platform', duration: '1 week', phase: 'advanced', topics: ['Architecture Doc', 'Monitoring', 'Deployment', 'Performance Tuning'] },
    ],
    skills: ['Java', 'Spring Boot', 'REST APIs', 'SQL', 'Hibernate', 'Microservices', 'JUnit', 'Docker'],
    projects: [
      { title: 'Banking Backend Platform', description: 'Build secure account, transfer, and audit APIs with role controls.', technologies: ['Java', 'Spring Boot', 'PostgreSQL', 'JWT'], image: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=500' },
      { title: 'E-commerce API Suite', description: 'Multi-service architecture for orders, payments, and inventory.', technologies: ['Java', 'Spring Cloud', 'Redis', 'Kafka'], image: 'https://images.unsplash.com/photo-1556742111-a301076d9d18?w=500' },
      { title: 'Loan Origination Service', description: 'Design and implement credit workflow APIs with scoring, approval, and audit pipelines.', technologies: ['Java', 'Spring Boot', 'MySQL', 'Redis'], image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=500' },
      { title: 'Inventory and Fulfillment Engine', description: 'Build resilient inventory APIs with retries, event queues, and observability dashboards.', technologies: ['Java', 'Kafka', 'PostgreSQL', 'Prometheus'], image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500' },
    ],
    batchInfo: { nextBatchDate: getNextBatchDate(), seatsAvailable: 17, totalSeats: 30 },
    learningFormat: {
      mode: 'Live + Recorded',
      batchOptions: ['Weekend Batch', 'Weekday Evening Batch'],
      groupSize: '20-25 students per batch',
      doubtsResolution: 'Live mentor sessions + async support',
      communityAccess: 'Lifetime access to Java backend learner community',
      liveSessionDuration: '2 hours per session',
      additionalSupport: 'Architecture review for capstone projects',
    },
    prerequisites: {
      required: ['Basic programming logic', 'Comfort with syntax learning', 'Commitment to coding practice'],
      recommended: ['Any prior language exposure', 'Database basics', 'Command line familiarity'],
      idealFor: ['CS graduates', 'Backend aspirants', 'Developers moving to Java stack'],
    },
    cost: 'Starting at ₹1,499',
    costDetails: {
      foundation: { name: 'Foundation', price: '₹1,499', duration: '3 months', features: ['Recorded modules', 'Community support', '3 practice projects'] },
      professional: { name: 'Professional', price: '₹4,999', duration: '3 months', features: ['Live classes', '5 projects', 'Resume and interview prep'] },
      premium: { name: 'Premium', price: '₹7,999', duration: '3 months', features: ['1-on-1 mentorship', 'Capstone guidance', 'Priority placement support'] },
    },
    pricingComparison: [
      { feature: 'Program Duration', foundation: '3 months', professional: '3 months', premium: '3 months' },
      { feature: 'Content Access', foundation: 'Foundation only', professional: 'All levels', premium: 'All levels' },
      { feature: 'Live Sessions', foundation: '❌', professional: '40+ hours', premium: '60+ hours' },
      { feature: 'Hands-on Projects', foundation: '3 projects', professional: '5 projects', premium: '8+ projects' },
      { feature: 'Capstone Project', foundation: '❌', professional: '❌', premium: '✅' },
      { feature: '1-on-1 Mentorship', foundation: '❌', professional: '❌', premium: '✅ Unlimited' },
      { feature: 'Interview Preparation', foundation: '❌', professional: 'Basic', premium: 'Advanced + Mock' },
      { feature: 'Placement Assistance', foundation: '❌', professional: 'Basic', premium: '✅ 100%' },
      { feature: 'Resume Building', foundation: '❌', professional: '✅', premium: '✅ + LinkedIn' },
      { feature: 'Industry Certifications', foundation: '1 certification', professional: '2 certifications', premium: '3+ certifications' },
      { feature: 'Job Referrals', foundation: '❌', professional: '❌', premium: '✅ Priority' },
      { feature: 'Lifetime Access', foundation: '✅', professional: '✅', premium: '✅' },
      { feature: 'Community Support', foundation: 'Forum only', professional: '✅ Active', premium: '✅ + Alumni Network' },
    ],
    competitorComparison: [
      { feature: 'Price', venura: '₹4,999 - ₹7,999', coursera: '₹18,000+', udemy: '₹4,500', bootcamp: '₹1,80,000+' },
      { feature: 'Duration', venura: '3 months', coursera: '3 months', udemy: '3 months', bootcamp: '3 months' },
      { feature: 'Live Sessions', venura: '60+ hours', coursera: 'Limited', udemy: 'None', bootcamp: 'High' },
      { feature: 'Placement Support', venura: '100% (Premium)', coursera: 'None', udemy: 'None', bootcamp: 'Yes' },
      { feature: '1-on-1 Mentorship', venura: 'Unlimited (Premium)', coursera: 'None', udemy: 'None', bootcamp: 'Limited' },
      { feature: 'Real Projects', venura: '8+ projects', coursera: '2-3 projects', udemy: '4-5 projects', bootcamp: '5-6 projects' },
      { feature: 'Job Referrals', venura: '100+ partners', coursera: 'None', udemy: 'None', bootcamp: '50+ partners' },
      { feature: 'Community', venura: 'Active 820+', coursera: 'Forum only', udemy: 'Limited', bootcamp: 'Batch only' },
      { feature: 'Certification', venura: 'Industry recognized', coursera: 'University backed', udemy: 'Platform certificate', bootcamp: 'Industry recognized' },
    ],
    jobRoles: ['Java Backend Developer', 'API Engineer', 'Spring Boot Developer', 'Software Engineer'],
    salaryRanges: [
      { role: 'Java Developer', range: '₹5-11 LPA', experience: '0-2 years' },
      { role: 'Backend Engineer', range: '₹6-13 LPA', experience: '0-2 years' },
      { role: 'Spring Boot Developer', range: '₹6-12 LPA', experience: '0-2 years' },
      { role: 'API Engineer', range: '₹7-13 LPA', experience: '0-2 years' },
      { role: 'Microservices Developer', range: '₹7-14 LPA', experience: '0-2 years' },
      { role: 'Software Engineer', range: '₹6-12 LPA', experience: '0-2 years' },
    ],
    hiringCompanies: ['Infosys', 'TCS', 'Wipro', 'Accenture', 'Cognizant', 'Oracle', 'IBM'],
    growthStats: [
      { value: '27%', label: 'Annual Growth', description: 'Enterprise backend role growth' },
      { value: '800K+', label: 'Open Roles', description: 'Backend opportunities across markets' },
      { value: 'Top 5', label: 'Most Stable Domain', description: 'Java remains core in enterprise systems' },
    ],
    marketDataSource: [
      { label: 'Stack Overflow Developer Survey', url: 'https://survey.stackoverflow.co/' },
      { label: 'LinkedIn Economic Graph', url: 'https://economicgraph.linkedin.com/' },
      { label: 'Oracle Java Ecosystem', url: 'https://www.oracle.com/java/' },
    ],
    comparisonSource: [
      { label: 'Coursera Pricing', url: 'https://www.coursera.org/' },
      { label: 'Udemy Pricing', url: 'https://www.udemy.com/' },
      { label: 'Bootcamp Listings', url: 'https://www.coursereport.com/' },
    ],
    futureOutlook: 'Java backend remains a durable and high-demand track for enterprise software, fintech systems, and mission-critical applications.',
    instructors: [
      { name: 'Ritesh Kulkarni', role: 'Lead Java Instructor', experience: '13+ years', credentials: 'Ex-Oracle', image: 'https://ui-avatars.com/api/?name=Ritesh+Kulkarni&background=0A2342&color=fff&size=200', specialization: 'Spring Architecture' },
      { name: 'Pooja Saini', role: 'Senior Backend Mentor', experience: '10+ years in distributed systems', credentials: 'Ex-Flipkart Platform Team', image: 'https://ui-avatars.com/api/?name=Pooja+Saini&background=FF7A00&color=fff&size=200', specialization: 'Microservices & Scalability' },
      { name: 'Nitin Arora', role: 'Industry Mentor', experience: '11+ years in API engineering', credentials: 'Ex-Infosys Fintech Practice', image: 'https://ui-avatars.com/api/?name=Nitin+Arora&background=0A2342&color=fff&size=200', specialization: 'Spring Security & APIs' },
    ],
    reviews: [
      { name: 'Manoj', role: 'Backend Engineer', company: 'Infosys', image: 'https://ui-avatars.com/api/?name=Manoj&background=0A2342&color=fff&size=200', rating: 5, text: 'Strong curriculum and practical assignments helped me clear interviews quickly.' },
      { name: 'Snehal Patil', role: 'Java Developer', company: 'TCS', image: 'https://ui-avatars.com/api/?name=Snehal+Patil&background=FF7A00&color=fff&size=200', rating: 5, text: 'The Spring Boot and API modules were exactly what interviews tested. Great mentor support throughout.' },
      { name: 'Vivek Shah', role: 'Software Engineer', company: 'Cognizant', image: 'https://ui-avatars.com/api/?name=Vivek+Shah&background=0A2342&color=fff&size=200', rating: 5, text: 'I gained confidence in Java backend architecture and finally moved from support to engineering role.' },
      { name: 'Harini Rao', role: 'API Engineer', company: 'Accenture', image: 'https://ui-avatars.com/api/?name=Harini+Rao&background=FF7A00&color=fff&size=200', rating: 5, text: 'Capstone and code reviews improved my design thinking. The placement prep sessions were very useful.' },
    ],
    certificatePreview: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
    faqs: [
      { question: 'Is Java still worth learning?', answer: 'Yes, especially for enterprise backend systems and long-term engineering careers.' },
      { question: 'Do I learn Spring Boot deeply?', answer: 'Yes, it is a core focus with multiple API and project implementations.' },
      { question: 'Will I build microservices projects?', answer: 'Yes. You will work on multi-service projects with gateways, messaging, and observability patterns.' },
      { question: 'Can I switch plans during the program?', answer: 'Yes, plan upgrades are available anytime by paying only the difference.' },
      { question: 'What if I miss live sessions?', answer: 'Every live class recording is available for lifetime access and revision.' },
      { question: 'Do you provide placement support?', answer: 'Premium includes end-to-end support: resume, mock interviews, and partner referrals.' },
      { question: 'How much weekly practice is needed?', answer: 'We recommend 8-10 hours for Foundation and 12-15 hours for Professional/Premium.' },
    ],
  }

  return <ProgramDetailTemplate programData={programData} />
}

export default JavaBackendPage
